common:
    workers: 4

    num_points: 1024
    num_classes: 40
    batch_size: 32
    
    base_lr: 0.001
    lr_clip: 0.00001
    lr_decay: 0.7
    decay_step: 21
    epochs: 200

    weight_decay: 0
    bn_momentum: 0.9
    bnm_clip: 0.01
    bn_decay: 0.5
    
    evaluate: 1
    val_freq_epoch: 0.5   # frequency in epoch for validation, can be decimal
    print_freq_iter: 20   # frequency in iteration for printing infomation
    
    input_channels: 0     # feature channels except (x, y, z)
    
    checkpoint: 'log-baseline/cls_iter_48042_acc_0.921799.pth'
    #'log-baseline/model_cls_L6_iter_36567_acc_0.923825_ori_bkup.pth'        # the model to start from
    
    save_path: log-baseline
    data_root: ../../Datasets
